#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 18 10:14:32 2020

@author: tlewitt
"""

from pathlib import Path

from DataGenerator import DataGen

###Input Parameters###
NU = 0.3
CORRELATION_LENGTH = 1
ALPHA_LN = 1.0
BETA_LN = 0.1
NUM_SNAPSHOTS = 1000
NUM_TEST_SNAPSHOTS = 10000

SAVE_DIR = Path("data/txt_files/")
'''
NOTE: When creating hdf5 files with the text files generated by this script, 
you MUST use the same parameters as the ones listed below or risk CERTAIN DOOOOOOOM.
'''
LENGTH = 1.0
WIDTH = 1.0
SIGMA = 1.5
NUM_TEST_POINTS_X = 25
NUM_TEST_POINTS_Y = 25
NUM_UX_SENSORS = 10
NUM_UY_SENSORS = 10
NUM_COLLOC_PTS_X = 10
NUM_COLLOC_PTS_Y = 10
NUM_U_BC_SENSORS = 10
NUM_SIGMA_BC_SENSORS = 10


data_gen = DataGen(NUM_TEST_POINTS_X, NUM_TEST_POINTS_Y, NUM_UX_SENSORS,
                   NUM_UY_SENSORS, NUM_COLLOC_PTS_X, NUM_COLLOC_PTS_Y,
                   NUM_U_BC_SENSORS, NUM_SIGMA_BC_SENSORS, LENGTH, WIDTH,
                   SIGMA)


#Generate and Save Train Txt Files
ux_train, uy_train, E_train = data_gen.generate_txt_data(True, NU,
                                                       CORRELATION_LENGTH,
                                                       ALPHA_LN, BETA_LN, 
                                                       NUM_SNAPSHOTS, NUM_TEST_SNAPSHOTS)
data_gen.save_txt_files(ux_train, uy_train, E_train, True)

#Generate and Save Test Txt Files
ux_test, uy_test, E_test = data_gen.generate_txt_data(False, NU,
                                                       CORRELATION_LENGTH,
                                                       ALPHA_LN, BETA_LN, 
                                                       NUM_SNAPSHOTS, NUM_TEST_SNAPSHOTS)
data_gen.save_txt_files(ux_test, uy_test, E_test, True)

